import { BACKGROUND_COLOR, LAYOUT_MAX_WIDTH } from '@/utils/const';
import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Header from './header';
import { Suspense } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PhimMoiDaDen',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box bgcolor={BACKGROUND_COLOR} pt={10} maxWidth={LAYOUT_MAX_WIDTH} minHeight="100vh" mx="auto">
            <Suspense>
              <Header />
              {children}
            </Suspense>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
